In [1]:
# # Evandro Ribeiro Gomes Coelho
# # TCCII

# packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics as m

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_regression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler 
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer

In [2]:
# # import data

fl_path = 'data/'
fl_ext = '.csv'

fl_name = 'df_mlp'
df = pd.DataFrame(pd.read_csv(fl_path + fl_name + fl_ext, sep=','))

del fl_path, fl_ext, fl_name

In [3]:
df = df.set_index('Timestamp')
df['Value Prev'] = df.Value.shift(1)
df['Temperature Prev'] = df.Temperature.shift(1)
df = df.fillna(0)
df

,Value,Temperature,Holiday Flag,hour,min,time,hr_sin,hr_cos,Value Prev,Temperature Prev
Timestamp,,,,,,,,,,
2015-07-03 14:30:00+00:00,6997.984367,31.0,0.0,14,30,14.5,-0.608761,-0.793353,0.000000,0.0
2015-07-03 15:30:00+00:00,15518.012898,33.0,0.0,15,30,15.5,-0.793353,-0.608761,6997.984367,31.0
2015-07-03 16:30:00+00:00,6674.491991,34.0,0.0,16,30,16.5,-0.923880,-0.382683,15518.012898,33.0
2015-07-03 17:30:00+00:00,4920.282616,33.0,0.0,17,30,17.5,-0.991445,-0.130526,6674.491991,34.0
2015-07-03 18:30:00+00:00,4118.787012,34.0,0.0,18,30,18.5,-0.991445,0.130526,4920.282616,33.0
...,...,...,...,...,...,...,...,...,...,...
2017-11-08 09:30:00+00:00,9823.167728,6.0,0.0,9,30,9.5,0.608761,-0.793353,9907.625408,5.0
2017-11-08 10:30:00+00:00,9813.048374,6.0,0.0,10,30,10.5,0.382683,-0.923880,9823.167728,6.0
2017-11-08 11:30:00+00:00,11714.319199,7.0,0.0,11,30,11.5,0.130526,-0.991445,9813.048374,6.0
2017-11-08 12:30:00+00:00,9209.390022,7.0,0.0,12,30,12.5,-0.130526,-0.991445,11714.319199,7.0
2017-11-08 13:30:00+00:00,8134.792530,7.0,0.0,13,30,13.5,-0.382683,-0.923880,9209.390022,7.0

In [4]:
model = Pipeline([
    ('scaler', MinMaxScaler(feature_range=(-1, 1), copy=True)),
    ('regressor', MLPRegressor(
    hidden_layer_sizes=(50,),  activation='tanh', solver='adam', alpha=0.001, batch_size='auto',
    learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=10000, shuffle=True,
    random_state=0, tol=0.0001, verbose=False, warm_start=False, momentum=0, nesterovs_momentum=True,
    early_stopping=True, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08, n_iter_no_change=10, max_fun=15000))
])

parameters = {
    'regressor__hidden_layer_sizes':[(1,),(2,),(3,),(4,),(5,),(6,),(7,),(8,),(9,),(10,),
                                     (11,),(12,),(13,),(14,),(15,),(16,),(17,),(18,),(19,),(20,),
                                     (21,),(22,),(23,),(24,),(25,),(26,),(27,),(28,),(29,),(30,),
                                     (31,),(32,),(33,),(34,),(35,),(36,),(37,),(38,),(39,),(40,),
                                     (41,),(42,),(43,),(44,),(45,),(46,),(47,),(48,),(49,),(50,)]
}

grid = GridSearchCV(
    model,
    parameters,
    scoring='r2',
    n_jobs = -1,
    cv = 10,
    verbose=True
)

In [5]:
features = ['Temperature', 'Temperature Prev','Value Prev','hr_sin','hr_cos', 'Holiday Flag']
X = df[features].values
y = df['Value']

In [6]:
# spliting data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [7]:
grid.fit(X_train, y_train)
frame = pd.DataFrame(grid.cv_results_)
frame.to_csv('data/frame-neurons-1500.csv', index = False, header=True)
frame

Fitting 10 folds for each of 50 candidates, totalling 500 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed: 11.5min
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed: 45.8min
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed: 89.0min
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed: 97.6min finished

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_regressor__hidden_layer_sizes,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,218.449126,6.052027,0.002137,0.001365,"(1,)","{'regressor__hidden_layer_sizes': (1,)}",-0.042872,-0.054509,-0.020392,-0.042531,-0.040271,-0.013440,-0.028228,-0.030338,-0.016489,-0.028682,-0.031775,0.012456,50
1,153.281613,21.370619,0.003561,0.003694,"(2,)","{'regressor__hidden_layer_sizes': (2,)}",-0.023693,-0.032466,-0.007488,-0.030997,-0.029187,-0.008777,-0.016535,-0.014813,-0.009056,-0.023312,-0.019632,0.009084,49
2,102.227955,2.168750,0.003598,0.002846,"(3,)","{'regressor__hidden_layer_sizes': (3,)}",-0.010262,-0.016833,-0.001075,-0.012046,-0.020733,-0.005325,-0.012129,-0.009613,-0.003256,-0.011527,-0.010280,0.005651,48
3,85.254790,2.289537,0.002790,0.002847,"(4,)","{'regressor__hidden_layer_sizes': (4,)}",-0.011245,-0.017011,-0.001282,-0.015378,-0.013358,-0.002653,-0.008974,-0.005255,-0.001678,-0.008605,-0.008544,0.005426,47
4,77.978110,2.597667,0.006576,0.007351,"(5,)","{'regressor__hidden_layer_sizes': (5,)}",-0.004976,-0.009404,-0.000007,-0.008762,-0.010189,-0.001639,-0.008017,-0.007195,-0.001494,-0.004520,-0.005620,0.003454,45
5,66.176277,2.235786,0.002509,0.001362,"(6,)","{'regressor__hidden_layer_sizes': (6,)}",-0.008206,-0.012574,-0.000250,-0.009327,-0.014468,-0.002708,-0.008421,-0.006142,-0.001815,-0.005669,-0.006958,0.004348,46
6,60.921532,1.769025,0.005650,0.006033,"(7,)","{'regressor__hidden_layer_sizes': (7,)}",-0.004813,-0.008679,-0.000114,-0.004479,-0.010397,-0.001125,-0.004704,-0.003198,-0.000959,-0.005544,-0.004401,0.003134,43
7,55.671683,0.792683,0.002234,0.000411,"(8,)","{'regressor__hidden_layer_sizes': (8,)}",-0.002773,-0.006055,-0.000650,-0.003015,-0.006717,-0.000126,-0.003120,-0.003062,-0.000188,-0.002540,-0.002825,0.002117,42
8,53.285115,2.386253,0.003343,0.001758,"(9,)","{'regressor__hidden_layer_sizes': (9,)}",-0.004334,-0.008504,-0.000090,-0.007800,-0.007330,-0.000671,-0.007219,-0.004468,-0.001297,-0.006752,-0.004847,0.003010,44
9,48.162102,1.133368,0.002602,0.000427,"(10,)","{'regressor__hidden_layer_sizes': (10,)}",-0.004597,-0.008234,-0.000156,-0.004303,-0.005225,-0.000030,-0.002259,-0.001131,-0.000012,-0.001308,-0.002725,0.002619,41
10,67.491056,72.325084,0.002704,0.000456,"(11,)","{'regressor__hidden_layer_sizes': (11,)}",-0.002518,-0.006221,-0.000697,0.612790,-0.006257,-0.000183,-0.002577,-0.000842,-0.000055,-0.001432,0.059201,0.184542,40
11,278.074962,28.343101,0.002694,0.000396,"(12,)","{'regressor__hidden_layer_sizes': (12,)}",0.634465,0.630842,0.640436,0.696958,0.650274,0.616168,0.586578,0.638339,0.619317,0.592780,0.630616,0.029438,28
12,187.260607,17.669502,0.003910,0.001771,"(13,)","{'regressor__hidden_layer_sizes': (13,)}",0.695060,0.701515,0.730843,0.733836,0.702999,0.690281,0.701398,0.671359,0.693010,0.679256,0.699956,0.018782,27
13,145.122481,4.682795,0.003694,0.002094,"(14,)","{'regressor__hidden_layer_sizes': (14,)}",0.753434,0.756529,0.759296,0.759516,0.774654,0.784923,0.756085,0.778630,0.762379,0.771120,0.765657,0.010313,26
14,132.823215,13.759911,0.003403,0.000806,"(15,)","{'regressor__hidden_layer_sizes': (15,)}",0.756520,0.768760,0.774276,0.758120,0.798677,0.794537,0.758609,0.774628,0.762369,0.753036,0.769953,0.015047,25
15,132.831733,14.679092,0.004359,0.001293,"(16,)","{'regressor__hidden_layer_sizes': (16,)}",0.757865,0.768864,0.771797,0.776227,0.790768,0.795345,0.761407,0.780961,0.782769,0.779521,0.776552,0.011325,23
16,123.350524,7.493138,0.004056,0.001306,"(17,)","{'regressor__hidden_layer_sizes': (17,)}",0.770413,0.770857,0.772979,0.799592,0.797292,0.804561,0.768212,0.776813,0.784540,0.788649,0.783391,0.012808,21
17,115.459759,7.684376,0.004605,0.001433,"(18,)","{'regressor__hidden_layer_sizes': (18,)}",0.768051,0.774906,0.772230,0.822347,0.799670,0.795358,0.817276,0.794417,0.785205,0.790325,0.791979,0.017150,19
18,106.495190,4.383438,0.003256,0.000430,"(19,)","{'regressor__hidden_layer_sizes': (19,)}",0.774902,0.776560,0.769352,0.788950,0.813974,0.804702,0.767681,0.807934,0.792086,0.803779,0.789992,0.016251,20
19,100.087454,4.813737,0.004285,0.000772,"(20,)","{'regressor__hidden_layer_sizes': (20,)}",0.765292,0.779472,0.795871,0.822328,0.817469,0.823835,0.777458,0.806543,0.803307,0.824132,0.801571,0.020333,18
20,102.379229,8.190652,0.004797,0.001317,"(21,)","{'regressor__hidden_layer_sizes': (21,)}",0.808551,0.807572,0.823056,0.830528,0.852899,0.852526,0.816670,0.842336,0.825056,0.830522,0.828972,0.015451,17
21,110.188057,8.612632,0.006995,0.008706,"(22,)","{'regressor__hidden_layer_sizes': (22,)}",0.813341,0.828989,0.841084,0.827851,0.851521,0.840199,0.840186,0.850276,0.846037,0.831801,0.837129,0.011137,14
22,101.986650,7.072616,0.004239,0.000509,"(23,)","{'regressor__hidden_layer_sizes': (23,)}",0.800345,0.834132,0.819777,0.829791,0.848287,0.841094,0.817416,0.835087,0.833136,0.839408,0.829847,0.013194,16
23,105.217932,6.490867,0.004401,0.001937,"(24,)","{'regressor__hidden_layer_sizes': (24,)}",0.807906,0.806874,0.819096,0.838271,0.847757,0.860808,0.819942,0.850440,0.845893,0.844727,0.834171,0.018136,15
24,97.962041,5.579293,0.004689,0.001364,"(25,)","{'regressor__hidden_layer_sizes': (25,)}",0.823900,0.827855,0.836162,0.841343,0.860404,0.865825,0.831187,0.851638,0.847179,0.828125,0.841362,0.013761,13
25,92.711100,3.963420,0.004490,0.000632,"(26,)","{'regressor__hidden_layer_sizes': (26,)}",0.838237,0.839429,0.840029,0.845178,0.859160,0.860199,0.844738,0.844756,0.838729,0.839848,0.845030,0.007740,12
26,95.802676,4.580950,0.004590,0.000660,"(27,)","{'regressor__hidden_layer_sizes': (27,)}",0.839594,0.841728,0.838538,0.847924,0.873245,0.857313,0.837573,0.856435,0.858054,0.844806,0.849521,0.010916,11
27,75.778717,29.808504,0.004352,0.000544,"(28,)","{'regressor__hidden_layer_sizes': (28,)}",-0.004200,-0.007599,-0.000037,0.844262,0.863604,0.871613,0.839205,0.866803,0.856513,0.838947,0.596911,0.393498,38
28,68.267772,24.269416,0.005200,0.001171,"(29,)","{'regressor__hidden_layer_sizes': (29,)}",-0.001713,-0.004585,-0.001055,0.849106,0.875640,0.873278,0.842397,0.857048,0.854317,0.848638,0.599307,0.394066,37
29,69.083438,26.005378,0.004402,0.000677,"(30,)","{'regressor__hidden_layer_sizes': (30,)}",-0.001579,-0.004251,-0.001328,0.853671,0.876337,0.874825,0.845007,0.865112,0.854716,0.842685,0.600520,0.394834,36
30,89.879286,5.432791,0.004892,0.000795,"(31,)","{'regressor__hidden_layer_sizes': (31,)}",0.839369,0.846022,0.859928,0.853732,0.873257,0.872252,0.848958,0.859912,0.860406,0.851552,0.856539,0.010295,10
31,91.219485,3.763042,0.005651,0.001543,"(32,)","{'regressor__hidden_layer_sizes': (32,)}",0.849196,0.849841,0.861621,0.853519,0.878634,0.876937,0.849886,0.865759,0.863513,0.847699,0.859661,0.010939,8
32,77.089057,29.554987,0.005305,0.001283,"(33,)","{'regressor__hidden_layer_sizes': (33,)}",-0.001419,-0.004520,-0.001511,0.854585,0.878097,0.872501,0.848479,0.870177,0.868053,0.848425,0.603287,0.396682,34
33,89.619451,3.564280,0.006107,0.001633,"(34,)","{'regressor__hidden_layer_sizes': (34,)}",0.840043,0.850254,0.861010,0.851998,0.873962,0.872675,0.850242,0.870672,0.865961,0.845102,0.858192,0.011610,9
34,78.312581,29.624417,0.005499,0.000654,"(35,)","{'regressor__hidden_layer_sizes': (35,)}",-0.001440,-0.004047,-0.001432,0.855456,0.882537,0.876519,0.849481,0.865851,0.866887,0.847507,0.603732,0.396880,33
35,67.550355,24.626138,0.005785,0.001883,"(36,)","{'regressor__hidden_layer_sizes': (36,)}",-0.001621,-0.004764,-0.001012,0.854728,0.881033,0.875686,0.850903,0.865868,0.865826,0.829811,0.601646,0.395709,35
36,51.185788,25.433039,0.004199,0.002138,"(37,)","{'regressor__hidden_layer_sizes': (37,)}",-0.002107,0.853195,-0.001070,0.854730,-0.004469,-0.000039,-0.001786,0.867548,0.871940,0.848068,0.428601,0.430544,39
37,75.307220,17.983307,0.007190,0.003396,"(38,)","{'regressor__hidden_layer_sizes': (38,)}",0.850038,0.850929,-0.000093,0.858603,0.877084,0.877013,0.852815,0.870714,0.866025,0.846294,0.774942,0.258567,24
38,81.162946,4.710033,0.005791,0.000986,"(39,)","{'regressor__hidden_layer_sizes': (39,)}",0.849492,0.853845,0.865317,0.855436,0.877972,0.872199,0.852284,0.869032,0.871987,0.848461,0.861602,0.010303,6
39,75.210030,3.550497,0.005286,0.002445,"(40,)","{'regressor__hidden_layer_sizes': (40,)}",0.849439,0.850391,0.864676,0.854820,0.881155,0.879327,0.852364,0.872361,0.869941,0.852469,0.862694,0.011695,3
40,59.847056,22.312577,0.006049,0.003192,"(41,)","{'regressor__hidden_layer_sizes': (41,)}",-0.000782,-0.003427,-0.001833,0.858533,0.881585,0.881235,0.854302,0.868821,0.870905,0.846787,0.605613,0.397920,29
41,72.565858,8.474137,0.006648,0.003247,"(42,)","{'regressor__hidden_layer_sizes': (42,)}",0.853527,0.853603,0.866512,0.860256,0.880195,0.878967,0.849750,0.869684,0.870596,0.837950,0.862104,0.012829,5
42,83.388586,4.376437,0.005884,0.002113,"(43,)","{'regressor__hidden_layer_sizes': (43,)}",0.852412,0.852297,0.865833,0.860429,0.884664,0.878778,0.854778,0.873569,0.869772,0.849406,0.864194,0.011642,1
43,59.779040,21.605645,0.005950,0.003669,"(44,)","{'regressor__hidden_layer_sizes': (44,)}",-0.000654,-0.003355,-0.002203,0.855861,0.880948,0.876675,0.852395,0.869972,0.872250,0.846118,0.604801,0.397425,31
44,56.952148,21.208078,0.005452,0.004631,"(45,)","{'regressor__hidden_layer_sizes': (45,)}",-0.000967,-0.003619,-0.001944,0.859993,0.879486,0.876391,0.848913,0.870044,0.871308,0.851543,0.605115,0.397675,30
45,51.797245,18.035948,0.005484,0.007035,"(46,)","{'regressor__hidden_layer_sizes': (46,)}",-0.001186,-0.003744,-0.002231,0.855395,0.880632,0.874807,0.854146,0.864786,0.867426,0.849940,0.603997,0.397070,32
46,63.749052,13.588047,0.006248,0.007653,"(47,)","{'regressor__hidden_layer_sizes': (47,)}",0.847898,0.853785,-0.002494,0.859113,0.882038,0.880594,0.851923,0.870939,0.871758,0.853103,0.776866,0.260048,22
47,69.736881,5.333815,0.006947,0.007364,"(48,)","{'regressor__hidden_layer_sizes': (48,)}",0.852982,0.850487,0.868713,0.855566,0.883214,0.878889,0.855495,0.873651,0.869883,0.845205,0.863409,0.012402,2
48,76.686428,4.568075,0.006248,0.007653,"(49,)","{'regressor__hidden_layer_sizes': (49,)}",0.848064,0.850750,0.864537,0.853047,0.884248,0.876601,0.851545,0.869177,0.872134,0.851645,0.862175,0.012190,4
49,69.693597,8.385482,0.005285,0.006990,"(50,)","{'regressor__hidden_layer_sizes': (50,)}",0.846647,0.844649,0.866814,0.858996,0.882539,0.873594,0.848358,0.869866,0.867343,0.849555,0.860836,0.012422,7